title: Huỳnh Phương Duy # your name (or website title) here
logo: "/cat.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science enthusiast. Proficient in - PowerBi, Python, SQL and intermediate knowledge in R
  <br><br>
  Fourth year student pursuing a degree in Corporate Finance from the University of Economics and Finance
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
